### ISSUE TITLE
Create add book page

### ISSUE THREAD

**Issue by coding-books** [coding-books/website#3]
Admin: can everything.
Moder: can add book, edit book and everything, which can user and guests
User and guests: can add book, download, view book, read online

Book: 
name 
seo_description
url
language
read_online_url
download_url
views_count
img

**Comment by BoBRoID** [comment]
Рекомендую вывод и вёрстку сделать Мише, если осилит - и права

**Comment by coding-books** [comment]
@BoBRoID Please, speak English

**Comment by BoBRoID** [comment]
Раздели на посмотр и добавление/редактирование

**Comment by coding-books** [comment]
@BoBRoID Please, speak English. I don't understand you

**Comment by coding-books** [comment]
Book: 
name 
seo_description
url
language
read_online_url
download_url

**Comment by coding-books** [comment]
@BoBRoID Mihail makes the layout, and you can do action for this case
