### ISSUE TITLE
онлайн-чтение

### ISSUE THREAD

**Issue by BoBRoID** [coding-books/website#5]
берёшь, делаешь консольный скрипт, который пройдётся по твоим файлам  книг (в приоритете, от rtf и pdf до всяких ebook), и вытягивает из них текст
добавляешь текст в бд на каждую книгу
и добавляешь онлайн-чтение

**Comment by Kravalg** [comment]
@BoBRoID This task will be implemented with the [Mozilla PDF.js](https://github.com/mozilla/pdf.js/)
